### ISSUE TITLE
Currency converter plugin 💰

### ISSUE THREAD

**Issue by ziulev** [ziulev/spotter#25]
Example queries: 
* 1000 euro in usd
* 1 rub in euro

**Comment by jitunayak** [comment]
i am running this on mac os big sur 11.1 . Seems it is broken ⚙️😢

**Comment by ziulev** [comment]
@jitunayak It's not implemented yet.
Feel free to create a new PR 🙂

**Comment by jitunayak** [comment]
@ziulev 
<img width="728" alt="Screenshot 2021-03-04 at 11 11 43 PM" src="https://user-images.githubusercontent.com/35754866/110006105-3d500c80-7d3f-11eb-9b9f-7229c88eaa95.png">

I put a simple currency conversion logic. I am not using any API (all paid ). it can only convert from dollar to other International currencies.

Could you help me showing the result in a list instead of as a single item ? I am very new to development. If you can guide me I will be an active contributor ❤️

Thanks you! for your amazing work

**Comment by ziulev** [comment]
1. We need to use API (for example [exchangeratesapi.io](https://exchangeratesapi.io/))
2. To display multiple options your plugin's onQuery method should return an array of multiple items instead of array with single one. (for example check [music plugin](https://github.com/ziulev/spotter/blob/master/src/plugins/music/music.plugin.ts))

And thank you for supporting the project! 🤍

**Comment by jitunayak** [comment]
@ziulev Thanks a lot, I will create a PR ASAP :)

**Comment by ziulev** [comment]
https://user-images.githubusercontent.com/14956407/115906409-c7774000-a467-11eb-935e-b8066458ec01.mov

https://github.com/ziulev/spotter/releases/tag/1.0.6

**Comment by ziulev** [comment]
@stefanosandes @city17 @russkirk @jitunayak 
Guys please test and let me know if have any issues/questions/suggestions 🚀

**Comment by jitunayak** [comment]
@ziulev Good Job Man!  You have nicely architected it. For some reason latest build is failing to install on mac os 11.2.3. I will build it on my machine and let you know.

**Comment by stefanosandes** [comment]
@ziulev humm.. let's say that.. my Spotlight is very sad haha!! Awesome work man, very very cool!
