### ISSUE TITLE
📕 Dictionary Plugin

### ISSUE THREAD

**Issue by diego-mari** [ziulev/spotter#73]
Adding a plugin for word definition instead of opening the dictionary app

**Comment by Zaitam** [comment]
You mean a dictionary Plugin?

**Comment by diego-mari** [comment]
yeah, implement some of the feature of the original spotlight. btw I can't open spotter's preferences

**Comment by Zaitam** [comment]
First, the plugin, currenty the development is turning towards an api which should force to re-implement all done plugins. In the case that it takes more than expected I will take hands in the matter.
Also if possible rename the issue to something more descriptibe, for example `📕 Dictionary Plugin`

Second, the preferences problem, how are you trying to open it? With the status bar item?

**Comment by diego-mari** [comment]
Also I noticed that the app name is not capitalize (spotter instead of Spotter, like other apps do)

**Comment by Zaitam** [comment]
The capitalized was not be done as `npx create-react-app`doesn't let to add Upper case on names.
Any how, the application's export name could be changes problemless (I think).
However, @ziulev should take oppinion on it

**Comment by ziulev** [comment]
Hey @diego-mari 👋

Could you be more specific about how you would like this plugin to work?
i.e. describe examples of queries and examples of results and if possible, with screenshots 

* Because spotlight, as you mentioned, produces results right inside itself. Do you want to achieve the same behaviour?
If so, at the moment there is no such possibility.

**Comment by ziulev** [comment]
Closing for now
