### ISSUE TITLE
Can't open apps in ~/Applications

### ISSUE THREAD

**Issue by exiva** [ziulev/spotter#86]
Apps installed in ~/Applications show up as unknown icons, and won't open.

Using 2.0.0-beta.16 

<img width="703" alt="Screen Shot 2021-12-18 at 12 28 59 AM" src="https://user-images.githubusercontent.com/56931/146630421-ecf23d27-65f0-4692-b933-72bd6a551120.png">

**Comment by ziulev** [comment]
Hey @exiva 

It looks like it works in the latest [version](https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.18)
Can you check please?

---
Also, please make sure you don't have applications plugins installed, because I've moved it to spotter.
Otherwise, you will have duplicated applications

**Comment by exiva** [comment]
Sorry about that, been busy. Does work now. I had duplicate entries, but resolved by removing the applications plugin by going to plugins > tab > applications > tab  > remove
